### ISSUE TITLE
Q: Should form formid be unique?

### ISSUE THREAD

**Issue by clint-tseng** [nafundi/jubilant-garbanzo#1]
Probably yes because the way submissions work is by formid, so we don't know how to target otherwise.

**Comment by lognaturel** [comment]
Yes, it should be unique.

**Comment by matthew-white** [comment]
Not that we have to decide this right now, but if we have two separate tables, one for forms and one for form versions, we can probably keep the uniqueness constraint. If we use a linked link approach with a `previous_version_id` column or something along those lines, that might be trickier.

For the different form versions, form ID + version should probably also be unique, right? These constraints are making me lean toward two tables&hellip...
