### ISSUE TITLE
Testing scheme for database calls

### ISSUE THREAD

**Issue by matthew-white** [nafundi/jubilant-garbanzo#10]
Clint writes:

> - Devise a testing scheme for &hellip; database calls that elude straightforward unit testing.
> - Unit test more/all of the surface area we have imported already.

You could also split this into two issues if that's easier&hellip;

**Comment by matthew-white** [comment]
Just thought I'd check, since #29 removed the tests, this issue is still open, right?

**Comment by clint-tseng** [comment]
Closing this; we aren't doing this this way.
