### ISSUE TITLE
Update behavior of merge()

### ISSUE THREAD

**Issue by matthew-white** [nafundi/jubilant-garbanzo#11]
My vote would be to have `merge()` in `util.js` match the behavior of `Object.assign()` and spread syntax: I think any differences could be confusing. Right now, `merge()` automatically concatenates values that are arrays (rather than replacing them) and will not replace a value with `null` or `undefined`. In most cases, I think we'd want `merge()` to fully replace values. An implementation could maybe we as simple as:

```javascript
const merge = (...objs) => Object.assign({}, ...objs);
```

Alternatively, perhaps we could have `merge` take an options parameter...

Thoughts?

**Comment by clint-tseng** [comment]
Do it.

**Comment by clint-tseng** [comment]
Though note that your proposed behavioural change will I think break the current schema derivation algorithm.
