### ISSUE TITLE
Error handling backstop / don't send stack traces

### ISSUE THREAD

**Issue by matthew-white** [nafundi/jubilant-garbanzo#22]
Right now, in some cases, if a request causes the server to throw an error, the stack trace is sent back as the response. How about we add error handling such that such cases result in a 500 response as JSON rather than a stack trace? I think that even if the JavaScript has a syntax error, tries to reassign a `const`, etc., that shouldn't result in a stack trace sent to the end user.

**Comment by clint-tseng** [comment]
Why not, though? It’s open source, it’s an API, and it could help us debug
the issue if someone encounters something unexpected.

**Comment by clint-tseng** [comment]
This is exactly what `cxlt/auth` does, to my knowledge.

**Comment by clint-tseng** [comment]
that branch is now merged.
