### ISSUE TITLE
Base.prototype.update() always resolves with false

### ISSUE THREAD

**Issue by matthew-white** [nafundi/jubilant-garbanzo#25]
This may be on @clint-tseng's radar already, but right now, I think `Base.prototype.update()` always resolves the promise with `false`. `db.update()` seems to resolve the promise with the number of affected rows, not an object with a `rowCount` property. For example:

```javascript
> const { connect } = require('./lib/model/database');
> const db = connect();
> db.
    update({ xmlFormId: 'newFormId' }).
    into('forms').
    where({ id: 1 }).
    then(result => console.log(result));
1 // Not { rowCount: 1 }
```

Since `Base.prototype.update()` looks for a `rowCount` property but will never find one, I think the promise will always resolve with `false`.

**Comment by clint-tseng** [comment]
Yeah, not sure what happened here. This is fixed now.
