### ISSUE TITLE
Add OpenRosa endpoints

### ISSUE THREAD

**Issue by matthew-white** [nafundi/jubilant-garbanzo#30]

**Comment by matthew-white** [comment]
@clint-tseng, this was implemented in https://github.com/nafundi/jubilant-garbanzo/pull/39, right?

**Comment by clint-tseng** [comment]
yeah, i'm not sure what this ticket would represent. i'm closing it.

**Comment by matthew-white** [comment]
I think this is just something that came up in one of our weekly calls that I created a placeholder ticket for. I think you implemented many OpenRosa endpoints in #39, so I think we can just keep OpenRosa in mind going forward.

**Comment by clint-tseng** [comment]
No reason to keep anything in mind, every single piece of required functionality is covered in the criteria.
