### ISSUE TITLE
Reduce xmlFormId field length to 64 characters.

### ISSUE THREAD

**Issue by matthew-white** [nafundi/jubilant-garbanzo#4]
We're making the form ID column in the database a `VARCHAR`, so we need to determine a maximum length. What is an appropriate maximum? (Is there a maximum?)

**Comment by matthew-white** [comment]
@lognaturel, what do you think an appropriate maximum length for form ID would be? Right now it's 255 characters, but we could extend that (or remove the limit altogether) or alternatively reduce it if it's unnecessarily long.

**Comment by clint-tseng** [comment]
I can't imagine >128 is necessary, and I'd advocate for 64. But I am not the expert!

**Comment by lognaturel** [comment]
While @clint-tseng is probably right, the safest would be to match current Aggregate which I believe caps at 250. I'd go for 255. Again, this is not because I expect it commonly gets very long but because there are probably already forms out there with really long IDs.

**Comment by lognaturel** [comment]
Are there any downsides to it being long? Even if it were an index I don't think the performance hit would be significant and I imagine indexes will be synthetic?

**Comment by clint-tseng** [comment]
The record length on-disk is directly impacted by `varchar` length, which in turn has cascading effects on backup WAL log size.

**Comment by lognaturel** [comment]
Is that really a big issue?

Honestly I've never seen an ID more than 32 characters or so. Another approach we could take is to start with 64 because we can't really imagine a form id longer than that which would be meaningful and we can ask for feedback once we have a beta out.

I hardly qualify as an expect...

**Comment by matthew-white** [comment]
It doesn't sound like any of us have super strong opinions, so I'd advocate for what @lognaturel suggests: let's change the column to 64 characters then see if we run into any trouble. Given @lognaturel's experience, it sounds like we should be safe with 64 characters.
