### ISSUE TITLE
Vue.js browser compatibility

### ISSUE THREAD

**Issue by matthew-white** [nafundi/jubilant-garbanzo#5]
@clint-tseng and I are thinking of starting out with [Vue.js](https://vuejs.org/). It supports "all browsers that are ES5-compliant (IE8 and below are not supported)" (see [here](https://github.com/vuejs/vue#browser-compatibility)). I think that should be fine, especially since Jubilant will be the server component, but we wanted to double-check that that'd work alright&hellip;

**Comment by lognaturel** [comment]
That table starts with IE11, does that mean that versions under 11 are shimmed?

I actually really don't have a good sense of how modern of browsers folks have access to but I've definitely seen some IE8 out there. @yanokwa is probably the one to ask.

**Comment by matthew-white** [comment]
Just to update this issue, it's not clear at first that IE9–11 are supported when you check the [compatibility table](https://kangax.github.io/compat-table/es5/) that Vue links to, but if you check "Show obsolete platforms," they appear. After inspecting analytics numbers for Build and the main ODK website, it looks like IE and especially old versions of IE are a small fraction of usage, so we're comfortable with these compatibility constraints.
