### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by matthew-white** [nafundi/jubilant-garbanzo#6]
This should be Apache License 2.0, right?

**Comment by lognaturel** [comment]
Yes!

**Comment by lognaturel** [comment]
I think the details of applying Apache 2 are at http://www.apache.org/dev/apply-license.html#new

https://softwarefreedom.org/resources/2012/ManagingCopyrightInformation.html is a really great article. My preference would be to follow their suggestions for centralized copyright notices and license notices. @yanokwa does that work?

**Comment by lognaturel** [comment]
Getting the license and copyright files in place as well as the header is enough for now. But we really should have a CLA across ODK - http://producingoss.com/en/copyright-assignment.html
