### ISSUE TITLE
Responses from /forms with extended metadata

### ISSUE THREAD

**Issue by matthew-white** [nafundi/jubilant-garbanzo#68]
I'm noticing a couple of null fields in responses from `/forms` when I request extended metadata:

- `formId`. I see that `forApi()` in `instance/form.js` excludes the `id` field. I think the null value is coming from `submission_stats.formId`.
- `submissions`. This seems to be null rather than zero when there are no submissions. I could see a case being made for either one, but I'd lean toward returning zero.

This isn't blocking anything on the Adventure side, but I thought I'd mention it as a possible future to-do.

**Comment by clint-tseng** [comment]
hm, i had the null/zero thing fixed at some point, and even had a test for it. i'm not sure where that went.
