### ISSUE TITLE
CLI: user-create error

### ISSUE THREAD

**Issue by matthew-white** [nafundi/jubilant-garbanzo#73]
I think we've seen this before, so this may be on @clint-tseng's radar already, but FYI, I'm seeing an error when I run `node lib/cli.js user-create`:

```
$ node lib/cli.js -u user@example.com -p password user-create
Required parameter displayName missing.
{ field: 'displayName' }
```

It was an easy fix, and this isn't blocking anything, but I just wanted to make sure we had an issue filed.

**Comment by clint-tseng** [comment]
Fixed in c7ca2d5618ed7775beaa0a7014f14b9141644189
